from .nf_ltx_audio_plugin import (
    NODE_CLASS_MAPPINGS as AUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nf_person_mask_node import (
    NODE_CLASS_MAPPINGS as PERSON_MASK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PERSON_MASK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nf_mmaudio_align_node import (
    NODE_CLASS_MAPPINGS as MMAUDIO_ALIGN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MMAUDIO_ALIGN_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(AUDIO_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PERSON_MASK_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MMAUDIO_ALIGN_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PERSON_MASK_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MMAUDIO_ALIGN_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
